image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

before_script:
  - 'if [ -z "$CI_COMMIT_TAG" ]; then export IMAGE_TAG="$CI_COMMIT_SHORT_SHA"; else export IMAGE_TAG="$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA"; fi'
  - "export IMAGE_NAME=$HARBOR_HOST/$HARBOR_PROJECT/$CI_PROJECT_NAME:$IMAGE_TAG"

build:
  stage: build
  script:
    - docker login -u "$HARBOR_USERNAME" -p "$HARBOR_PASSWORD" $HARBOR_HOST
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
    - 'if [ -n "$CI_COMMIT_TAG" ]; then docker tag $IMAGE_NAME $HARBOR_HOST/$HARBOR_PROJECT/$CI_PROJECT_NAME:latest; docker push $HARBOR_HOST/$HARBOR_PROJECT/$CI_PROJECT_NAME:latest; fi'
  tags:
    - fluxus-docker-builder

deploy:
  stage: deploy
  script:
    - docker login -u "$HARBOR_USERNAME" -p "$HARBOR_PASSWORD" $HARBOR_HOST
    - docker pull $IMAGE_NAME
    - echo "IMAGE_NAME=$IMAGE_NAME" > .env
    - cp $PRODUCTION_ENV > claymore.env
    - docker-compose up -d
  tags:
    - fluxus-sg-docker
