image: docker:20.10.16

services:
  - docker:20.10.16-dind

stages:
  - build
  - deploy

variables:
  DOCKER_TLS_CERTDIR: "/certs"

before_script:
  - 'if [ -z "$CI_COMMIT_TAG" ]; then export IMAGE_TAG="$CI_COMMIT_SHORT_SHA"; else export IMAGE_TAG="$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA"; fi'
  - "export IMAGE_NAME=$HARBOR_HOST/$HARBOR_PROJECT/$CI_PROJECT_NAME:$IMAGE_TAG"
  - "export LATEST_IMAGE=$HARBOR_HOST/$HARBOR_PROJECT/$CI_PROJECT_NAME:latest"
  - docker info

build:
  stage: build
  script:
    - docker login -u "$HARBOR_USERNAME" -p "$HARBOR_PASSWORD" $HARBOR_HOST
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
    - 'if [ -z "$CI_COMMIT_TAG" ]; then docker tag $IMAGE_NAME $LATEST_IMAGE; docker push $LATEST_IMAGE; fi'
  tags:
    - fluxus-docker-builder

deploy:
  stage: deploy
  script:
    - docker login -u "$HARBOR_USERNAME" -p "$HARBOR_PASSWORD" $HARBOR_HOST
    - docker pull $IMAGE_NAME
    - echo "IMAGE_NAME=$LATEST_IMAGE" > .env
    - cp $PRODUCTION_ENV claymore.env
    - docker compose up -d
  tags:
    - fluxus-sjc-shell
    - epyc
  only:
    - main

deploy-dev:
  stage: deploy
  script:
    - docker login -u "$HARBOR_USERNAME" -p "$HARBOR_PASSWORD" $HARBOR_HOST
    - docker pull $LATEST_IMAGE
    - echo "IMAGE_NAME=$LATEST_IMAGE" > .env
    - cp $PRODUCTION_ENV claymore.env
    - docker compose up -d
  tags:
    - fluxus-hz-dev-shell
  only:
    - dev
