image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

before_script:
  - 'if [ -z "$CI_COMMIT_TAG" ]; then export IMAGE_TAG="$CI_COMMIT_SHORT_SHA"; else export IMAGE_TAG="$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA"; fi'
  - "export IMAGE_NAME=$HARBOR_URL/$HARBOR_PROJECT/$CI_PROJECT_NAME:$IMAGE_TAG"

build:
  stage: build
  script:
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" registry.mydomain.com
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
    - 'if [ -n "$CI_COMMIT_TAG" ]; then docker tag $IMAGE_NAME registry.mydomain.com/myproject:latest; docker push registry.mydomain.com/myproject:latest; fi'
  tags:
    - runnerA
  when: manual

deploy:
  stage: deploy
  script:
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" registry.mydomain.com
    - docker pull $IMAGE_NAME
    - echo "IMAGE_NAME=$IMAGE_NAME" > .env
    - docker-compose up -d
  tags:
    - runnerB
  when: manual

envs:
  stage: build
  script:
    - echo $PRODUCTION_ENV
    - docker login -u "$HARBOR_USERNAME" -p "$HARBOR_PASSWORD" $HARBOR_HOST
    - echo "$HARBOR_URL/$HARBOR_PROJECT/$CI_PROJECT_NAME"
    - echo $IMAGE_NAME
  tags:
    - fluxus-sg-docker
  when: manual
