version: '3.8'

services:
  claymore-api:
    image: ${IMAGE_NAME}
    ports:
      - "127.0.0.1:9000:8080"
    env_file:
      - claymore.env
    networks:
      - claymore_backend_network
    restart: always
    depends_on:
      - claymore-db
      - claymore-rabbitmq
    volumes:
      - /opt/claymore:/var/claymore

  claymore-db:
    image: postgres:latest
    volumes:
      - claymore_backend_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=fluxus
      - POSTGRES_PASSWORD=fluxus
      - POSTGRES_DB=claymore_backend
    restart: always
    networks:
      - claymore_backend_network

  claymore-rabbitmq:
    image: rabbitmq:3-management
    restart: always
    networks:
      - claymore_backend_network
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
  
  claymore-unstructured:
    image: downloads.unstructured.io/unstructured-io/unstructured-api:latest
    restart: always
    networks:
      - claymore_backend_network
    command: --port 8000 --host 0.0.0.0

  claymore-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    networks:
      - claymore_backend_network
    volumes:
      - claymore_es_data:/usr/share/elasticsearch/data

networks:
  claymore_backend_network:
    driver: bridge

volumes:
  claymore_backend_data:
  claymore_es_data: